### ISSUE TITLE
thanks and a couple of questions

### ISSUE THREAD

**Issue by lakamsani** [hjanuschka/fastlane-plugin-upload_symbols_to_new_relic#2]
Hi @hjanuschka , thanks for writing this plugin. I have been invoking this script to upload my dsyms to NR https://gist.github.com/chrislavender/e2daf0a21f23f4b8e1d0 but would like to switch over to your plugin. I have two questions. 

First related to your plugin. For dsym_path, I 'm guessing I can just pass in lane_context[SharedValues::DSYM_OUTPUT_PATH]? Can you clarify what the new_relic_upload_libs is used for? The zip file usually contains dSYMS for all dependent pods so what is the typical use of new_relic_upload_libs setting?

Second is a general fastlane question but somewhat related to New Relic uploading (have this issue even with the script I currently use). I have multiple apps in New Relic and so I specify the app ids in scheme/target specific user defined setting (called NEW_RELIC_ID) in my XCode project. In the gym log file in ~/Library/Logs/gym I can see that it initializes and  prints this variable correctly for the target being built like this:

export NEW_RELIC_ID=xxxxx

However, if I try to grab is via ENV['NEW_RELIC_ID'] it comes up blank. I 'd like to pass it to new_relic_license_key setting of your plugin.

**Comment by hjanuschka** [comment]
@lakamsani 
- `DSYM_OUTPUT_PATH` should be set automatically. 
- new_relic_upload_libs - you can set a comma seperated list of libs wich should be included, default should be empty - wich means everything is uploaded (i guess this is the most common case)
- have you tried setting the env inside the fastfile ? like `ENV['NEW_RELIC_ID'] ='xxxx'`

**Comment by hjanuschka** [comment]
can you run `fastlane env`  to get a clue about your setup ?

**Comment by lakamsani** [comment]
So looks like I can completely skip the entries dsym_path and new_relic_upload_libs and it will do the right things from the gym context (i.e. use its DSYM_OUTPUT_PATH and grab all the libs). Only new_relic_license_key and new_relic_app_name are required settings to your plugin. I will give that a shot. That definitely simplifies and brings it close to the upload_symbols_to_crashlytics action in how it works. 

On the NEW_RELIC_ID, the problem is that unlike Fabric/Crashlytics New Relic requires the api key to be supplied in my app code using NewRelicAgent.startWithApplicationToken. So I need this in the XCode build settings and access it via NSBundle.mainBundle().infoDictionary.  If the same can be accessed in the lane it would be perfect. It is definitely printing it in gym logs. So I wonder why the lane can't get it. I would rather not to repeat this key via en explicit variable setting in my Fastfile. The other problem with setting to one value  in the fastfile is that I have 10 or so new relic ids. So it can't be static. For Fabric API key, I 'm indeed setting it in one place in an env file used by Fastfile.

**Comment by hjanuschka** [comment]
you can try getting the value via 

``` ruby
relic_key = get_info_plist_value(path: plist_file_path, key: 'CFBundleShortVersionString')
```

adopting the key for sure, and checking the path to plist file.

let me know if it works for you

**Comment by lakamsani** [comment]
Thanks for the suggestion. 
I ran into the problem described here. https://gist.github.com/phatblat/6f4410cbd8873738479e
and here: https://www.snip2code.com/Snippet/856253/Fastlane-Info-Plist

I need to get the plist file dynamically. Even if I get, there is just a single plist file per target. I have multiple XCode schemes per target (one for Development, one for Adhoc and one for AppStore) and each has its own new relic id. So for now I will explore grepping (via sh)  the gym build log file which is able to print the correct scheme specific value for the new relic app id. 

I was however able to confirm your plugin works by specifying just the two settings new_relic_license_key and new_relic_app_name like this. 

```
   # app is a hash with some app specific meta-data. The command to grab the nrKey always grabs the last one i.e. for the Release build config. parsing gym build logs to get the right one is the only solution I can think of for now. 
    nrAppId = app['nrAppId']
    scheme =  app['scheme']
    nrKey = sh("xcodebuild -workspace ../My.xcworkspace -scheme #{scheme} -showBuildSettings | grep NEW_RELIC_ID | sed 's/[ ]*NEW_RELIC_ID = //'").chomp

    upload_symbols_to_new_relic(
        new_relic_license_key: nrKey,
        new_relic_app_name: nrAppId
    )
```

**Comment by lakamsani** [comment]
Here is my lane that is doing everything I need. 

``` ruby
  desc "Upload dsyms to New Relic via upload_symbols_to_new_relic plugin"
  lane :newrelic do |options|
      nrAppId = options['nrAppId']
      scheme =  options['scheme']
#after gym command set options['logPath'] = Gym::BuildCommandGenerator.xcodebuild_log_path
      logPath =  options['logPath']
      pname = sh("xcodebuild -workspace ../My.xcworkspace -scheme #{scheme} -showBuildSettings  | grep -v FULL | grep PRODUCT_NAME | sed 's/[ ]*PRODUCT_NAME = //'").chomp
      nrKey = sh("grep NEW_RELIC_ID '#{logPath}' | tail -1 | sed 's/export NEW_RELIC_ID=//'").chomp
      puts "  #{nrKey} #{nrAppId}"
      unless nrAppId.nil?
        upload_symbols_to_new_relic(
            new_relic_license_key: nrKey,
            new_relic_app_name: nrAppId
        )
      end

  end
```

**Comment by hjanuschka** [comment]
glad to hear  -  you got it working
